<?php

/**
 * hook_menu_link_alter
 */
function icid_helper_menu_link_alter(&$item) {
  $item['options']['html'] = TRUE;
}

/**
 * Implements hook_menu_alter().
 */
function icid_helper_menu_alter(&$items) {
  $items['user/register']['weight'] = 5;
  $items['user/password']['weight'] = 10;
}
/**
 * Implements hook_form_alter().
 */
function icid_helper_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  if ($form_id == 'webform_client_form_20' && $form['details']['page_num']['#value'] == '5') {

    $node = $form['#node'];
    foreach ($node->webform['components'] as $cid => $component) {
      if (isset($form_state['storage']['submitted'][$component['cid']])) {
        $$component['form_key'] = $form_state['storage']['submitted'][$component['cid']];
      }
    }

    $time = time();
    $cf_fee = $time < strtotime("2013-10-10") ? 1800 : 2000;
    $cf_fee = $registration_type == 1 ? 300 : $cf_fee;
    $ws_fee = 800;
    $bt_fee = 80;

    $main_conference_num = $group_people_num ? $group_people_num : 1;
    $workshop_count = $workshop ? $main_conference_num : 0;
    $ticket_count = $ticket_count ? $ticket_count : 0;

    //优惠价 8折
    if ($workshop) {
      $cf_fee = $cf_fee * 0.8;
      $ws_fee = $ws_fee * 0.8;
    }

    $cf_fees = $cf_fee * $main_conference_num;
    $ws_fees = $ws_fee * $workshop_count;
    $bt_fees = $bt_fee * $ticket_count;

    //团体价 满5减1
    if ($apply_for_group_price && $registration_type == 0) {
      $cf_fee = $time < strtotime("2013-9-30") ? 1800 : 2000;
      if ($workshop) {
        $cf_fee = $cf_fee * 0.8;
      }
      $num = $group_people_num >= 5 ? ceil($group_people_num * 0.8) : $group_people_num;
      $cf_fees = $cf_fee * $num;
      $ws_fees = $ws_fee * $num;
    }
    $total = $cf_fees + $ws_fees + $bt_fees;

    $registration_type = $registration_type ? '学生' : '成人';
    $markups = "<table>
                <tr>
                  <td>注册明细<br />Registration List</td>
                  <td>邮箱<br />Email</td>
                  <td>注册项目<br />Registration Type</td>
                </tr>
                <tr>
                  <td>$first_name $last_name</td>
                  <td>$user->mail</td>
                  <td>$registration_type</td>
                </tr>
              </table>";
    $markups .= "<table>
                  <tr>
                    <td>付费项目<br />Fees</td>
                    <td>数量<br />Quantity</td>
                    <td>费用<br />Unit Price</td>
                    <td>总结<br />Amount</td>
                  </tr>
                  <tr>
                    <td>ICID大会<br />Main Conference</td>
                    <td>$main_conference_num</td>
                    <td>RMB $cf_fee</td>
                    <td>RMB $cf_fees</td>
                  </tr>
                  <tr>
                    <td>主题研讨会 1<br />Workshop 1</td>
                    <td>$workshop_count</td>
                    <td>RMB $ws_fee</td>
                    <td>RMB $ws_fees</td>
                  </tr>
                  <tr>
                    <td>附加晚餐入场券<br />Additional Banquet Ticket</td>
                    <td>$ticket_count</td>
                    <td>RMB $bt_fee</td>
                    <td>RMB $bt_fees</td>
                  </tr>
                  <tr>
                    <td></td>
                    <td></td>
                    <td>总费用/Total</td>
                    <td>RMB $total</td>
                  </tr>
                </table>";
    $form['submitted']['confirmation']['#markup'] = $markups;
    $form['submitted']['apply_info']['#value'] = $markups;
    $form['submitted']['total_fees']['#value'] = $total;
  }
}

/**
 * Implements hook_menu().
 */
function icid_helper_menu() {
  $items['user/fees-info'] = array(
    'title' => '缴费信息',
    'page callback' => 'icid_helper_fees_info',
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}

function icid_helper_fees_info() {
  global $user;

  $result = db_select('webform_submissions', 'ws')
    ->fields('ws', array('sid'))
    ->condition('nid', 20)
    ->condition('uid', $user->uid)
    ->execute();

    $sids = array();
    foreach ($result as $row) {
      $sids[] = $row->sid;
      $submissions[$row->sid] = FALSE;
    }

    if (empty($sids)) {
      drupal_set_message('您还没有报名');
      drupal_goto('node/20');
    }

    drupal_goto('node/20/submission/' . $sids[0]);
}
